# Classical Chinese (文言文/古语) UI strings — keyed like gen_extended_i18n.T

GU: dict[str, str] = {
    "window_title": "Remote Sensing Qt Starter",
    "menu.data": "数籍",
    "menu.raster": "像图处置",
    "menu.index": "遥感指数",
    "menu.photogrammetry": "测绘 / 三维",
    "menu.streetview": "街景 / 全景",
    "menu.pointcloud": "点云处置",
    "menu.ai": "AI",
    "menu.settings": "设署",
    "menu.help": "指引",
    "action.load_raster": "载入像图（GDAL，可多择）",
    "action.load_pointcloud": "载入点云",
    "action.load_mesh": "载入网格",
    "action.load_dem": "载入 DEM",
    "action.delete_layer": "删所选图层",
    "action.clear_project": "清空工部",
    "action.settings": "语言 / Language...",
    "action.help_guide": "用式指南",
    "action.show_ai": "示 AI 佐",
    "layer_tree": "工图层级",
    "tab.2d": "二维像图",
    "tab.3d": "三维场景",
    "tab.panorama": "360° 全景",
    "tab.log": "录事",
    "tab.ai": "AI 佐",
    "settings.tab.general": "通设",
    "settings.title": "设署",
    "settings.language": "界面语言",
    "settings.theme": "主题色",
    "settings.care_mode": "颐养模式（大字）",
    "theme.pink": "淡粉红（默认）",
    "theme.light_blue": "淡蓝",
    "theme.light_green": "淡绿",
    "theme.lavender": "淡紫",
    "theme.warm_sand": "暖沙",
    "theme.mint": "薄荷",
    "settings.lang.zh": "中文",
    "settings.lang.en": "English",
    "settings.lang.ru": "俄文",
    "settings.lang.fr": "法文",
    "settings.lang.gu": "古语",
    "settings.tab.guide": "用式指南",
    "settings.tab.about": "关于",
    "settings.button": "设署",
    "log.startup": "Starter 已启：此版具 GDAL 多波段、参数化算法、DEM/正射之工架。",
    "menu.raster.band": "波段与设色",
    "menu.raster.stat": "统计",
    "menu.raster.enhance": "增强",
    "menu.raster.feature": "特征与检测",
    "menu.raster.classify": "分类与检测",
    "action.render": "波段组合 / 设色...",
    "action.histogram": "灰度直方图...",
    "action.equalize": "直方图均衡...",
    "action.stretch": "线性 / 百分拉伸...",
    "action.clahe": "CLAHE 增强...",
    "action.gaussian_filter": "高斯滤波...",
    "action.median_filter": "中值滤波...",
    "action.bilateral_filter": "双边滤波...",
    "action.unsharp": "Unsharp 锐化...",
    "action.laplacian_sharpen": "拉普拉斯锐化...",
    "action.feature_extract": "ORB/SIFT/AKAZE 特征提取...",
    "action.canny": "Canny 缘检测...",
    "action.kmeans": "K-Means 无监督分类...",
    "action.svm": "SVM 地物分类...",
    "action.contour": "轮廓目标检测...",
    "action.connected_components": "连通域目标检测...",
    "action.confusion_matrix": "混淆矩阵精度评...",
    "action.index_calc": "算 NDVI/NDWI/NDBI...",
    "action.index_temporal": "多时相指数对比...",
    "action.index_export_csv": "导出指数统计 CSV...",
    "action.water_area": "水体面积计算...",
    "action.infrared_spectral": "红外光谱分析...",
    "action.dem_rebuild": "DEM 重建...",
    "action.orthorectify": "正射像图校正...",
    "action.dem_texture": "DEM 三维贴图...",
    "action.load_panorama360": "载入 360 街景...",
    "action.voxel_downsample": "体素降采样...",
    "action.statistical_filter": "统计滤波...",
    "action.pointcloud_to_dem": "点云转 DEM...",
    "action.export_ply": "导出 PLY...",
    "action.delete_single_layer": "删图层",
    "action.export_layer": "导出...",
    "action.zoom_to_extent": "缩放至范围",
    "action.properties": "属性",
    "action.export_group": "导出该分组...",
    "tree.source_data": "源数",
    "tree.results": "处置成果",
    "tree.raster": "遥感像图",
    "tree.pointcloud": "点云",
    "tree.panorama360": "360° 全景",
    "tree.group.dem_rebuild": "DEM 重建",
    "tree.group.orthorectify": "正射校正",
    "tree.group.histogram": "直方图",
    "tree.group.confusion_matrix": "混淆矩阵",
    "tree.group.index_temporal": "多时相对比",
    "geo.title": "坐标已读",
    "geo.detected": "像中察有坐标信息。",
    "geo.file": "文件：",
    "geo.projection_snippet": "投影（WKT）片段：",
    "view.select_layer": "请先择一遥感像图图层或波段。",
    "view.no_render": "当前像图无可示渲染。\n现图层：%1",
    "dialog.select_export_dir": "择导出目录",
    "dialog.load_raster": "载入像图",
    "dialog.load_pointcloud": "载入点云",
    "dialog.load_mesh": "载入网格",
    "dialog.load_dem": "载入 DEM",
    "dialog.load_panorama": "载入 360 全景",
    "dialog.export_layer": "导出图层",
    "dialog.export_dem": "导出 DEM",
    "prop.title": "图层属性 — %1",
    "prop.name": "名：",
    "prop.path": "径：",
    "prop.type": "类：",
    "prop.visible": "可见：",
    "prop.yes": "是",
    "prop.no": "否",
    "prop.bands": "波段：",
    "prop.size_pixels": "尺寸：%1 × %2 像素",
    "prop.projection": "投影：",
    "prop.unknown": "（未知）",
    "prop.point_count": "点数：",
    "prop.vertices": "顶点：",
    "prop.triangles": "三角面：",
    "prop.size": "尺寸：%1 × %2",
    "prop.summary": "概要：",
    "type.raster": "遥感像图",
    "type.pointcloud": "点云",
    "type.mesh": "网格模型",
    "type.dem": "数字高程模型",
    "type.panorama360": "360° 全景",
    "type.result": "处置成果",
    "splash.title": "遥感像图处置平台",
    "splash.starting": "启中",
    "splash.team": "制作团队：CodeFour",
    "help.title": "用式指南",
    "log.no_previous_session": "未寻前次载入之数。",
    "log.restoring_session": "复旧数籍（%1 项）...",
    "log.restore_file_missing": "未果：文件未寻 [%1]",
    "log.restore_failed": "复旧未果 [%1]：%2",
    "log.restore_done": "复旧：成 %1，败 %2。",
    "log.raster_loaded": "像图已载入：%1（%2 波段，%3×%4）",
    "log.load_failed": "载入未果 [%1]：%2",
    "log.pointcloud_loaded": "点云已载入：%1（%2 点）",
    "log.pointcloud_load_failed": "点云载入未果 [%1]：%2",
    "log.mesh_loaded_vertices_only": "网格 %1（%2 顶点，无面）",
    "log.mesh_loaded": "网格 %1（%2 顶点，%3 面）",
    "log.mesh_vbo_hint": "网格于三维示之，VBO 启，法线平滑。",
    "log.mesh_load_failed": "网格载入未果 [%1]：%2",
    "log.dem_loaded": "DEM 已载入：%1（%2×%3）",
    "log.dem_load_failed": "DEM 载入未果 [%1]：%2",
    "log.panorama_qt_failed_gdal": "Qt 未读全景：%1；试 GDAL。",
    "log.panorama_gdal_failed": "GDAL 亦未果：%1",
    "log.panorama_ratio_hint": "360° 宽高比：%1:1（非 2:1）。",
    "log.panorama_loaded": "全景已载入：%1（%2×%3）",
    "log.panorama_load_method": "全景读法：%1",
    "log.layers_deleted": "已删图层：%1。",
    "log.project_cleared": "工部已清。",
    "log.render_failed": "渲染未果：%1",
    "log.render_done": "已示：%1，%2。",
    "log.select_raster": "请先择像图图层。",
    "log.select_raster_one": "请择一像图图层。",
    "log.select_two_rasters_ref": "请择二栅格（预测 + 参照）。",
    "log.select_two_temporal": "请择二异时栅格。",
    "log.select_layer": "请先择图层。",
    "log.select_stereo_pair": "请择立体像对（左、右）。",
    "log.select_raster_dem": "请择像图与 DEM。",
    "log.orthorectify_failed": "正射校正未果。",
    "log.select_raster_dem_texture": "请择像图与 DEM 以三维贴图。",
    "log.dem_texture_failed": "三维贴图未果：%1",
    "log.dem_texture_done": "三维贴图成：DEM=%1，纹理=%2，源=%3 %4",
    "log.export_ply_hint": "请择点云或网格。",
    "log.cannot_create_file": "未能建文件：%1",
    "log.export_pointcloud_ply": "PLY 已导出：%1（%2 点）",
    "log.export_mesh_ply": "网格 PLY 已导出：%1（%2 顶点，%3 面）",
    "log.export_not_pointcloud_mesh": "图层非点云或网格。",
    "log.export_failed": "导出未果：%1",
    "log.select_pointcloud": "请择点云。",
    "log.layer_shown": "%1：已示",
    "log.layer_hidden": "%1：已隐",
    "log.export_group_done": "已导出组内 %1/%2 图层。",
    "log.layer_deleted": "图层已删。",
    "log.zoom_todo_raster": "TODO：缩放至 %1",
    "log.zoom_extent": "已缩放至 %1。",
    "log.panorama_switched": "已切换全景：%1。",
    "log.zoom_todo": "TODO：缩放至 %1",
    "log.export_no_raster": "导出 [%1]：无像图。",
    "log.export_write_failed": "未能写入：%1",
    "log.export_raster_done": "已导出：%1 → %2",
    "log.export_dem_done": "DEM 已导出：%1 → %2",
    "log.export_dem_failed": "DEM 导出未果：%1",
    "log.export_no_panorama": "导出 [%1]：无全景。",
    "log.export_panorama_done": "全景已导出：%1 → %2",
    "log.export_unsupported": "导出 [%1]：类型未支持。",
}

HELP_GU = """
<h2>遥感像图处置平台 — 用式指南</h2>
<h3>一、速上手</h3>
<ol>
<li>于 <b>数籍</b> 菜单载入遥感像图、点云、网格或 DEM。</li>
<li>于左侧 <b>工图层级</b> 树中择图层。</li>
<li><b>二维像图</b> 标签示栅格；<b>三维场景</b> 示点云 / 网格。</li>
<li>底部 <b>录事</b> 面板察处置消息。</li>
</ol>
<h3>二、像图处置</h3>
<ul>
<li><b>波段与设色</b>：设波段组合与显色。</li>
<li><b>增强</b>：直方图均衡、拉伸、滤波、锐化等。</li>
<li><b>特征 / 分类</b>：ORB/SIFT、缘检测、K-Means、SVM 等。</li>
<li><b>遥感指数</b>：NDVI、NDWI、NDBI 及多时相对比。</li>
</ul>
<h3>三、三维与点云</h3>
<ul>
<li>载入点云或网格于三维标签。</li>
<li><b>点云处置</b>：降采样、滤波、转 DEM、导出 PLY。</li>
<li><b>测绘 / 三维</b>：DEM 重建、正射校正等。</li>
</ul>
<h3>四、街景 / 全景</h3>
<p>于 <b>街景 / 全景</b> 菜单载入 360° 全景，于专标签览之。</p>
<h3>五、AI 佐</h3>
<p>启窗口底部 <b>AI 佐</b> 标签，附图层信息以问。</p>
<h3>六、设署</h3>
<p>点右上 <b>设署</b> 按钮。<b>通设</b> 标签可换语言、主题色；<b>用式指南</b> 标签阅本手册。</p>
<h3>七、要诀</h3>
<ul>
<li>二维视图中 Ctrl + 滚轮可缩放像图。</li>
<li>图层树中 Ctrl/Shift 可多择图层。</li>
<li>处置成果添为新图层于工图树。</li>
</ul>
""".strip()
